/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 146,
					MAX_NAME_LENGTH = 41,
					NUM_STATES = 1340,

					NT_OFFSET = 146,
					SCOPE_UBOUND = 346,
					SCOPE_SIZE = 347,
					LA_STATE_OFFSET = 18789,
					MAX_LA = 1,
					NUM_RULES = 968,
					NUM_TERMINALS = 146,
					NUM_NON_TERMINALS = 436,
					NUM_SYMBOLS = 582,
					START_STATE = 1190,
					EOFT_SYMBOL = 71,
					EOLT_SYMBOL = 71,
					ACCEPT_ACTION = 18788,
					ERROR_ACTION = 18789;
}
