/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

import java.util.HashMap;
import java.util.Map;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public enum TerminalToken {

	// special tokens not part of grammar - not autogenerated
							TokenNameInvalid(-1),
							TokenNameNotAToken(0),
							TokenNameWHITESPACE(1000),
							TokenNameCOMMENT_LINE(1001),
							TokenNameCOMMENT_BLOCK(1002),
							TokenNameCOMMENT_JAVADOC(1003),
							TokenNameSingleQuoteStringLiteral(1004),
							TokenNameCOMMENT_MARKDOWN(1005),

	// BEGIN_AUTOGENERATED_REGION
							TokenNameIdentifier(30),
							TokenNameabstract(55),
							TokenNameassert(93),
							TokenNameboolean(109),
							TokenNamebreak(94),
							TokenNamebyte(110),
							TokenNamecase(111),
							TokenNamecatch(112),
							TokenNamechar(113),
							TokenNameclass(72),
							TokenNamecontinue(95),
							TokenNameconst(144),
							TokenNamedefault(90),
							TokenNamedo(96),
							TokenNamedouble(114),
							TokenNameelse(123),
							TokenNameenum(87),
							TokenNameextends(108),
							TokenNamefalse(42),
							TokenNamefinal(56),
							TokenNamefinally(122),
							TokenNamefloat(115),
							TokenNamefor(97),
							TokenNamegoto(145),
							TokenNameif(98),
							TokenNameimplements(140),
							TokenNameimport(116),
							TokenNameinstanceof(11),
							TokenNameint(117),
							TokenNameinterface(86),
							TokenNamelong(118),
							TokenNamenative(57),
							TokenNamenew(39),
							TokenNamenon_sealed(58),
							TokenNamenull(43),
							TokenNamepackage(107),
							TokenNameprivate(59),
							TokenNameprotected(60),
							TokenNamepublic(61),
							TokenNamereturn(99),
							TokenNameshort(119),
							TokenNamestatic(41),
							TokenNamestrictfp(62),
							TokenNamesuper(37),
							TokenNameswitch(65),
							TokenNamesynchronized(44),
							TokenNamethis(38),
							TokenNamethrow(91),
							TokenNamethrows(124),
							TokenNametransient(63),
							TokenNametrue(45),
							TokenNametry(100),
							TokenNamevoid(120),
							TokenNamevolatile(64),
							TokenNamewhile(92),
							TokenNamemodule(121),
							TokenNameopen(125),
							TokenNamerequires(126),
							TokenNametransitive(133),
							TokenNameexports(127),
							TokenNameopens(128),
							TokenNameto(141),
							TokenNameuses(129),
							TokenNameprovides(130),
							TokenNamewith(142),
							TokenNameCASE(134),
							TokenNameOTHERWISE(135),
							TokenNameELSE(131),
							TokenNameIF(101),
							TokenNameSWITCH(102),
							TokenNameIntegerLiteral(46),
							TokenNameLongLiteral(47),
							TokenNameFloatingPointLiteral(48),
							TokenNameDoubleLiteral(49),
							TokenNameCharacterLiteral(50),
							TokenNameStringLiteral(51),
							TokenNameTextBlock(52),
							TokenNamePLUS_PLUS(8),
							TokenNameMINUS_MINUS(9),
							TokenNameEQUAL_EQUAL(19),
							TokenNameEQUAL_EQUAL_EQUAL(20),
							TokenNameLESS_EQUAL(15),
							TokenNameGREATER_EQUAL(16),
							TokenNameNOT_EQUAL(21),
							TokenNameNOT_EQUAL_EQUAL(22),
							TokenNameLEFT_SHIFT(18),
							TokenNameRIGHT_SHIFT(12),
							TokenNameUNSIGNED_RIGHT_SHIFT(14),
							TokenNamePLUS_EQUAL(74),
							TokenNameMINUS_EQUAL(75),
							TokenNameMULTIPLY_EQUAL(76),
							TokenNameDIVIDE_EQUAL(77),
							TokenNameAND_EQUAL(78),
							TokenNameOR_EQUAL(79),
							TokenNameXOR_EQUAL(80),
							TokenNameREMAINDER_EQUAL(81),
							TokenNameLEFT_SHIFT_EQUAL(82),
							TokenNameRIGHT_SHIFT_EQUAL(83),
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL(84),
							TokenNameCONNECT(85),
							TokenNameOR_OR(29),
							TokenNameAND_AND(28),
							TokenNamePLUS(1),
							TokenNameMINUS(2),
							TokenNameNOT(66),
							TokenNameREMAINDER(6),
							TokenNameXOR(24),
							TokenNameAND(23),
							TokenNameMULTIPLY(4),
							TokenNameOR(25),
							TokenNameTWIDDLE(67),
							TokenNameDIVIDE(7),
							TokenNameGREATER(17),
							TokenNameLESS(5),
							TokenNameLPAREN(31),
							TokenNameRPAREN(32),
							TokenNameLBRACE(53),
							TokenNameRBRACE(36),
							TokenNameLBRACKET(13),
							TokenNameRBRACKET(103),
							TokenNameSEMICOLON(34),
							TokenNameQUESTION(27),
							TokenNameCOLON(73),
							TokenNameCOMMA(35),
							TokenNameDOT(3),
							TokenNameEQUAL(70),
							TokenNameAT(40),
							TokenNameELLIPSIS(136),
							TokenNameHASH(26),
							TokenNameARROW(132),
							TokenNameCOLON_COLON(10),
							TokenNameBeginLambda(89),
							TokenNameBeginIntersectionCast(68),
							TokenNameBeginTypeArguments(106),
							TokenNameAT308(33),
							TokenNameAT308DOTDOTDOT(143),
							TokenNameCaseArrow(105),
							TokenNameRestrictedIdentifierYield(104),
							TokenNameRestrictedIdentifierrecord(88),
							TokenNameRestrictedIdentifiersealed(54),
							TokenNameRestrictedIdentifierpermits(137),
							TokenNameBeginCasePattern(138),
							TokenNameRestrictedIdentifierWhen(139),
							TokenNameUNDERSCORE(69),
							TokenNameEOF(71),
							TokenNameERROR(146);

// END_AUTOGENERATED_REGION

	private final static Map<Integer, TerminalToken> tokenMap = new HashMap<>(256);
	static {
		for (TerminalToken t : TerminalToken.values()) {
			tokenMap.put(t.tokenNumber(), t);
		}
	}

	private final int tokenNumber;

	// Constructor
	TerminalToken(int number) {
		this.tokenNumber = number;
	}

	public int tokenNumber() {
		return this.tokenNumber;
	}

	public static boolean isRestrictedKeyword(TerminalToken tokenType) {
		return switch (tokenType) {
			case TokenNameRestrictedIdentifierYield, TokenNameRestrictedIdentifierrecord, TokenNameRestrictedIdentifierWhen,
					TokenNameRestrictedIdentifiersealed, TokenNameRestrictedIdentifierpermits -> true;
			default -> false;
		};
	}

	public static TerminalToken getRestrictedKeyword(char [] text) {
		if (text != null) {
			int len = text.length;
			if (len == 4 && text[0] == 'w' ||
				len == 5 && text[0] == 'y' ||
				len == 6 && (text[0] == 'r' || text[0] == 's') ||
				len == 7 && text[0] == 'p') {
				return getRestrictedKeyword(new String(text));
			}
		}
		return TokenNameNotAToken;
	}

	public static TerminalToken getRestrictedKeyword(String text) {
		return switch (text) {
			case "yield"   -> TokenNameRestrictedIdentifierYield;   //$NON-NLS-1$
			case "record"  -> TokenNameRestrictedIdentifierrecord;  //$NON-NLS-1$
			case "when"    -> TokenNameRestrictedIdentifierWhen;    //$NON-NLS-1$
			case "sealed"  -> TokenNameRestrictedIdentifiersealed;  //$NON-NLS-1$
			case "permits" -> TokenNameRestrictedIdentifierpermits; //$NON-NLS-1$
			default        -> TokenNameNotAToken;
		};
	}

	public static TerminalToken of(int act) {
		TerminalToken token = tokenMap.get(act);
		if (token == null) {
			// Really shouldn't occur -- perhaps if parser non-terminals are looked up?
			throw new IllegalArgumentException("Unknown token number = " + act); //$NON-NLS-1$
		}
		return token;
	}

	static TerminalToken maybeOf(int act) {
		return tokenMap.get(act);
	}

}

